// This file is automatically generated
// Generated on: 2025-05-13T00:00:00.000Z

// Article data
export const articles = [
  { 
    slug: "first-post", 
    hasCustomOgImage: false 
  },
  { 
    slug: "getting-started", 
    hasCustomOgImage: false 
  }
];

// Helper functions
export function getValidSlugs() {
  return articles.map(a => a.slug);
}

export function getArticleBySlug(slug) {
  return articles.find(a => a.slug === slug);
}