import fs from 'fs';
import path from 'path';

async function generateArticlesData() {
  // Instead of using glob, we'll directly list the known articles
  const articles = [
    { slug: "first-post", hasCustomOgImage: false },
    { slug: "getting-started", hasCustomOgImage: false }
  ];
  
  // Generate articles data file
  const content = `// This file is automatically generated
// Generated on: ${new Date().toISOString()}

// Article data
export const articles = [
  { 
    slug: "first-post", 
    hasCustomOgImage: false 
  },
  { 
    slug: "getting-started", 
    hasCustomOgImage: false 
  }
];

// Helper functions
export function getValidSlugs() {
  return articles.map(a => a.slug);
}

export function getArticleBySlug(slug) {
  return articles.find(a => a.slug === slug);
}`;
  
  // Write to the lib directory
  fs.writeFileSync('src/lib/articles.ts', content);
  console.log('✅ 已生成 src/lib/articles.ts');
}

generateArticlesData().catch(console.error);